using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace DNSYar.Services;

public sealed class UiText : INotifyPropertyChanged
{
    public static UiText Current { get; } = new();

    public string Language { get; private set; } = "fa";
    public bool IsEnglish => Language == "en";
    public bool IsRtl => Language != "en";

    public const string VazirmatnFamily = "ms-appx:///Assets/Fonts/Vazirmatn-Variable.ttf#Vazirmatn";
    public const string InterFamily = "ms-appx:///Assets/Fonts/InterVariable.ttf#Inter Variable";

    private Dictionary<string, string> _map = Fa;

    public void SetLanguage(string language)
    {
        Language = language == "en" ? "en" : "fa";
        _map = IsEnglish ? En : Fa;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
    }

    public string this[string key] => G(key);
    public string G(string key) => _map.TryGetValue(key, out var value) ? value : key;
    public string F(string key, params object[] args) => string.Format(G(key), args);

    public string NavHome => G(nameof(NavHome));
    public string NavAi => G(nameof(NavAi));
    public string NavDev => G(nameof(NavDev));
    public string NavGame => G(nameof(NavGame));
    public string NavAll => G(nameof(NavAll));
    public string NavSite => G(nameof(NavSite));
    public string NavSettings => G(nameof(NavSettings));
    public string BrandKicker => G(nameof(BrandKicker));
    public string Creator => G(nameof(Creator));
    public string HeroKicker => G(nameof(HeroKicker));
    public string HeroTitle => G(nameof(HeroTitle));
    public string HeroSubtitle => G(nameof(HeroSubtitle));
    public string TestAll => G(nameof(TestAll));
    public string SmartNow => G(nameof(SmartNow));
    public string RestoreDns => G(nameof(RestoreDns));
    public string MetricActive => G(nameof(MetricActive));
    public string MetricScore => G(nameof(MetricScore));
    public string MetricAdapter => G(nameof(MetricAdapter));
    public string MetricProviders => G(nameof(MetricProviders));
    public string MetricSmart => G(nameof(MetricSmart));
    public string Recommend => G(nameof(Recommend));
    public string RecommendEmpty => G(nameof(RecommendEmpty));
    public string RecommendHint => G(nameof(RecommendHint));
    public string Connect => G(nameof(Connect));
    public string Test => G(nameof(Test));
    public string AdapterTitle => G(nameof(AdapterTitle));
    public string AdapterHint => G(nameof(AdapterHint));
    public string Coverage => G(nameof(Coverage));
    public string AddCustom => G(nameof(AddCustom));
    public string TestSection => G(nameof(TestSection));
    public string SearchPlaceholder => G(nameof(SearchPlaceholder));
    public string GreenMeansOk => G(nameof(GreenMeansOk));
    public string SiteTitle => G(nameof(SiteTitle));
    public string SiteKicker => G(nameof(SiteKicker));
    public string SiteHint => G(nameof(SiteHint));
    public string SitePlaceholder => G(nameof(SitePlaceholder));
    public string SiteTested => G(nameof(SiteTested));
    public string SiteReachable => G(nameof(SiteReachable));
    public string SiteFailed => G(nameof(SiteFailed));
    public string SiteFastest => G(nameof(SiteFastest));
    public string SiteEmptyTitle => G(nameof(SiteEmptyTitle));
    public string SiteEmptyHint => G(nameof(SiteEmptyHint));
    public string SettingsTitle => G(nameof(SettingsTitle));
    public string SettingsSubtitle => G(nameof(SettingsSubtitle));
    public string LanguageTitle => G(nameof(LanguageTitle));
    public string LanguageHint => G(nameof(LanguageHint));
    public string AppearanceTitle => G(nameof(AppearanceTitle));
    public string AppearanceHint => G(nameof(AppearanceHint));
    public string FontLabel => G(nameof(FontLabel));
    public string ThemeLabel => G(nameof(ThemeLabel));
    public string FontHint => G(nameof(FontHint));
    public string FontAuto => G(nameof(FontAuto));
    public string ThemePaper => G(nameof(ThemePaper));
    public string ThemeInk => G(nameof(ThemeInk));
    public string ThemeSignal => G(nameof(ThemeSignal));
    public string SmartTitle => G(nameof(SmartTitle));
    public string SmartHint => G(nameof(SmartHint));
    public string SmartToggle => G(nameof(SmartToggle));
    public string ProfileLabel => G(nameof(ProfileLabel));
    public string IntervalLabel => G(nameof(IntervalLabel));
    public string MinScoreLabel => G(nameof(MinScoreLabel));
    public string FailuresLabel => G(nameof(FailuresLabel));
    public string ProfileAll => G(nameof(ProfileAll));
    public string ProfileAi => G(nameof(ProfileAi));
    public string ProfileDev => G(nameof(ProfileDev));
    public string ProfileGame => G(nameof(ProfileGame));
    public string MonitorStatus => G(nameof(MonitorStatus));
    public string RunNow => G(nameof(RunNow));
    public string SmartExplain => G(nameof(SmartExplain));
    public string TrayTitle => G(nameof(TrayTitle));
    public string TrayHint => G(nameof(TrayHint));
    public string TrayToggle => G(nameof(TrayToggle));
    public string CloseToTray => G(nameof(CloseToTray));
    public string ExitBehaviorTitle => G(nameof(ExitBehaviorTitle));
    public string ExitBehaviorMessage => G(nameof(ExitBehaviorMessage));
    public string TrayExplain => G(nameof(TrayExplain));
    public string CatalogTitle => G(nameof(CatalogTitle));
    public string CatalogHint => G(nameof(CatalogHint));
    public string AutoUpdateToggle => G(nameof(AutoUpdateToggle));
    public string CatalogKeepCustom => G(nameof(CatalogKeepCustom));
    public string UpdateUrlLabel => G(nameof(UpdateUrlLabel));
    public string DefaultSource => G(nameof(DefaultSource));
    public string UpdateIntervalLabel => G(nameof(UpdateIntervalLabel));
    public string DefaultSourceHint => G(nameof(DefaultSourceHint));
    public string CheckUpdate => G(nameof(CheckUpdate));
    public string RestoreTitle => G(nameof(RestoreTitle));
    public string RestoreHint => G(nameof(RestoreHint));
    public string RestoreOnExit => G(nameof(RestoreOnExit));
    public string CrashRecovery => G(nameof(CrashRecovery));
    public string RestoreNoteTitle => G(nameof(RestoreNoteTitle));
    public string RestoreNoteMessage => G(nameof(RestoreNoteMessage));
    public string RestoreAdapter => G(nameof(RestoreAdapter));
    public string RestoreAll => G(nameof(RestoreAll));
    public string AboutTitle => G(nameof(AboutTitle));
    public string AboutSubtitle => G(nameof(AboutSubtitle));
    public string AboutAuthor => G(nameof(AboutAuthor));
    public string AuthorName => G(nameof(AuthorName));
    public string LabelPing => G(nameof(LabelPing));
    public string LabelDns => G(nameof(LabelDns));
    public string LabelLoss => G(nameof(LabelLoss));
    public string LabelServices => G(nameof(LabelServices));
    public string Off => G(nameof(Off));
    public string On => G(nameof(On));
    public string Ready => G(nameof(Ready));
    public string Active => G(nameof(Active));
    public string CustomSource => G(nameof(CustomSource));
    public string ReadyToTest => G(nameof(ReadyToTest));
    public string Testing => G(nameof(Testing));
    public string StatusExcellent => G(nameof(StatusExcellent));
    public string StatusGood => G(nameof(StatusGood));
    public string StatusFair => G(nameof(StatusFair));
    public string StatusWeak => G(nameof(StatusWeak));
    public string Interval5 => G(nameof(Interval5));
    public string Interval10 => G(nameof(Interval10));
    public string Interval15 => G(nameof(Interval15));
    public string Interval30 => G(nameof(Interval30));
    public string Interval60 => G(nameof(Interval60));
    public string Score55 => G(nameof(Score55));
    public string Score65 => G(nameof(Score65));
    public string Score75 => G(nameof(Score75));
    public string Score85 => G(nameof(Score85));
    public string Failures1 => G(nameof(Failures1));
    public string Failures2 => G(nameof(Failures2));
    public string Failures3 => G(nameof(Failures3));
    public string Hours6 => G(nameof(Hours6));
    public string Hours12 => G(nameof(Hours12));
    public string Hours24 => G(nameof(Hours24));
    public string Hours72 => G(nameof(Hours72));
    public string CategoryAll => G(nameof(CategoryAll));
    public string ListTitleAll => G(nameof(ListTitleAll));
    public string ListTitleAi => G(nameof(ListTitleAi));
    public string ListTitleDev => G(nameof(ListTitleDev));
    public string ListTitleGame => G(nameof(ListTitleGame));
    public string ListSubAll => G(nameof(ListSubAll));
    public string ListSubAi => G(nameof(ListSubAi));
    public string ListSubDev => G(nameof(ListSubDev));
    public string ListSubGame => G(nameof(ListSubGame));
    public string BusyTesting => G(nameof(BusyTesting));
    public string LangFa => "فارسی";
    public string LangEn => "English";

    public event PropertyChangedEventHandler? PropertyChanged;
    private void OnChanged([CallerMemberName] string? name = null) =>
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));

    private static readonly Dictionary<string, string> Fa = new()
    {
        [nameof(NavHome)] = "خانه",
        [nameof(NavAi)] = "هوش مصنوعی",
        [nameof(NavDev)] = "برنامه‌نویسی",
        [nameof(NavGame)] = "بازی",
        [nameof(NavAll)] = "همه DNSها",
        [nameof(NavSite)] = "تست سایت",
        [nameof(NavSettings)] = "تنظیمات",
        [nameof(BrandKicker)] = "مدیر هوشمند DNS",
        [nameof(Creator)] = "سازنده",
        [nameof(HeroKicker)] = "Smart DNS · Windows",
        [nameof(HeroTitle)] = "بهترین مسیر را پیدا کن",
        [nameof(HeroSubtitle)] = "پینگ، Resolve و دسترسی واقعی سرویس‌های AI، توسعه و بازی را با هم مقایسه کن — بدون شلوغی.",
        [nameof(TestAll)] = "تست همه",
        [nameof(SmartNow)] = "Smart Auto الآن",
        [nameof(RestoreDns)] = "بازگشت DNS",
        [nameof(MetricActive)] = "DNS فعال",
        [nameof(MetricScore)] = "بهترین امتیاز",
        [nameof(MetricAdapter)] = "کارت شبکه",
        [nameof(MetricProviders)] = "DNSها",
        [nameof(MetricSmart)] = "Smart Auto",
        [nameof(Recommend)] = "پیشنهاد",
        [nameof(RecommendEmpty)] = "هنوز تست نشده",
        [nameof(RecommendHint)] = "«تست همه» را بزن تا بهترین گزینه مشخص شود.",
        [nameof(Connect)] = "اتصال",
        [nameof(Test)] = "تست",
        [nameof(AdapterTitle)] = "کارت شبکه",
        [nameof(AdapterHint)] = "DNS فقط روی کارت انتخاب‌شده اعمال می‌شود.",
        [nameof(Coverage)] = "پوشش تست",
        [nameof(AddCustom)] = "+ DNS دستی",
        [nameof(TestSection)] = "تست این بخش",
        [nameof(SearchPlaceholder)] = "جستجو: نام یا IP",
        [nameof(GreenMeansOk)] = "سبز = موفق",
        [nameof(SiteTitle)] = "تست سایت",
        [nameof(SiteKicker)] = "بدون تغییر DNS ویندوز",
        [nameof(SiteHint)] = "دامنه را وارد کن. هر DNS جداگانه Resolve می‌شود و اتصال واقعی HTTP بررسی می‌گردد.",
        [nameof(SitePlaceholder)] = "google.com  یا  https://chatgpt.com",
        [nameof(SiteTested)] = "تست‌شده",
        [nameof(SiteReachable)] = "قابل دسترسی",
        [nameof(SiteFailed)] = "ناموفق",
        [nameof(SiteFastest)] = "سریع‌ترین موفق",
        [nameof(SiteEmptyTitle)] = "یک دامنه وارد کن",
        [nameof(SiteEmptyHint)] = "نتیجه هر DNS زنده، سبز یا قرمز نمایش داده می‌شود.",
        [nameof(SettingsTitle)] = "تنظیمات",
        [nameof(SettingsSubtitle)] = "زبان، ظاهر، Smart Auto و بازگردانی امن",
        [nameof(LanguageTitle)] = "زبان",
        [nameof(LanguageHint)] = "رابط فارسی راست‌چین و انگلیسی چپ‌چین است. فونت مناسب همان زبان اعمال می‌شود.",
        [nameof(AppearanceTitle)] = "ظاهر",
        [nameof(AppearanceHint)] = "تم مینیمال و فونت‌های همراه برنامه",
        [nameof(FontLabel)] = "فونت",
        [nameof(ThemeLabel)] = "تم",
        [nameof(FontHint)] = "Vazirmatn برای فارسی و Inter برای انگلیسی داخل برنامه هستند. Segoe UI از ویندوز خوانده می‌شود.",
        [nameof(FontAuto)] = "خودکار (بر اساس زبان)",
        [nameof(ThemePaper)] = "Paper",
        [nameof(ThemeInk)] = "Ink",
        [nameof(ThemeSignal)] = "Signal",
        [nameof(SmartTitle)] = "Smart Auto + Failover",
        [nameof(SmartHint)] = "سوییچ فقط بعد از افت واقعی کیفیت",
        [nameof(SmartToggle)] = "انتخاب و Failover خودکار DNS",
        [nameof(ProfileLabel)] = "پروفایل",
        [nameof(IntervalLabel)] = "فاصله بررسی",
        [nameof(MinScoreLabel)] = "حداقل امتیاز جایگزین",
        [nameof(FailuresLabel)] = "Failover بعد از چند افت",
        [nameof(ProfileAll)] = "همه‌کاره",
        [nameof(ProfileAi)] = "هوش مصنوعی",
        [nameof(ProfileDev)] = "برنامه‌نویسی",
        [nameof(ProfileGame)] = "بازی",
        [nameof(MonitorStatus)] = "وضعیت پایش",
        [nameof(RunNow)] = "بررسی الآن",
        [nameof(SmartExplain)] = "ابتدا فقط DNS فعال تست می‌شود. اگر چند بار پشت‌سرهم افت کند، گزینه‌های همان پروفایل مقایسه و بهترین DNS سالم جایگزین می‌شود.",
        [nameof(TrayTitle)] = "System Tray",
        [nameof(TrayHint)] = "کنترل سریع کنار ساعت ویندوز",
        [nameof(TrayToggle)] = "آیکن DNSYar در System Tray",
        [nameof(CloseToTray)] = "× فقط پنجره را مخفی کند",
        [nameof(ExitBehaviorTitle)] = "رفتار خروج",
        [nameof(ExitBehaviorMessage)] = "پیش‌فرض خاموش است: × یعنی خروج کامل و بازگردانی DNS. اگر روشن باشد، × فقط مخفی می‌کند؛ خروج کامل از Tray همچنان DNS را بازیابی می‌کند.",
        [nameof(TrayExplain)] = "منو: DNS فعال، سوییچ سریع، Smart Auto، تست فوری، بازگردانی و خروج کامل.",
        [nameof(CatalogTitle)] = "بروزرسانی از GitHub",
        [nameof(CatalogHint)] = "ادغام امن با فهرست محلی",
        [nameof(AutoUpdateToggle)] = "دریافت خودکار DNSهای جدید",
        [nameof(CatalogKeepCustom)] = "DNSهای دستی با بروزرسانی GitHub حذف نمی‌شوند.",
        [nameof(UpdateUrlLabel)] = "آدرس فایل — JSON یا TXT",
        [nameof(DefaultSource)] = "منبع پیش‌فرض",
        [nameof(UpdateIntervalLabel)] = "فاصله بروزرسانی",
        [nameof(DefaultSourceHint)] = "منبع پیش‌فرض: Iran-DNS-Switcher / dns_servers.txt",
        [nameof(CheckUpdate)] = "بررسی الآن",
        [nameof(RestoreTitle)] = "بازگردانی امن",
        [nameof(RestoreHint)] = "حفظ تنظیم DNS قبل از DNSYar",
        [nameof(RestoreOnExit)] = "با بستن برنامه یا خاموش شدن ویندوز، DNS قبلی برگردد",
        [nameof(CrashRecovery)] = "اگر برنامه ناگهانی بسته شد، در اجرای بعد بازیابی شود",
        [nameof(RestoreNoteTitle)] = "نکته",
        [nameof(RestoreNoteMessage)] = "قبل از اولین تغییر، تنظیم واقعی کارت ذخیره می‌شود. DNS دستی قبلی برمی‌گردد؛ اگر DHCP بوده، دوباره DHCP فعال می‌شود.",
        [nameof(RestoreAdapter)] = "بازگشت کارت انتخابی",
        [nameof(RestoreAll)] = "بازگردانی همه",
        [nameof(AboutTitle)] = "درباره DNSYar",
        [nameof(AboutSubtitle)] = "مدیریت هوشمند DNS برای ویندوز",
        [nameof(AboutAuthor)] = "سازنده: سهند رضوان",
        [nameof(AuthorName)] = "سهند رضوان",
        [nameof(LabelPing)] = "پینگ",
        [nameof(LabelDns)] = "DNS",
        [nameof(LabelLoss)] = "تلفات",
        [nameof(LabelServices)] = "سرویس‌ها",
        [nameof(Off)] = "خاموش",
        [nameof(On)] = "فعال",
        [nameof(Ready)] = "آماده",
        [nameof(Active)] = "فعال",
        [nameof(CustomSource)] = "دستی · ذخیره محلی",
        [nameof(ReadyToTest)] = "آماده تست",
        [nameof(Testing)] = "در حال تست…",
        [nameof(StatusExcellent)] = "عالی",
        [nameof(StatusGood)] = "خوب",
        [nameof(StatusFair)] = "متوسط",
        [nameof(StatusWeak)] = "ضعیف",
        [nameof(Interval5)] = "هر ۵ دقیقه",
        [nameof(Interval10)] = "هر ۱۰ دقیقه",
        [nameof(Interval15)] = "هر ۱۵ دقیقه",
        [nameof(Interval30)] = "هر ۳۰ دقیقه",
        [nameof(Interval60)] = "هر ۶۰ دقیقه",
        [nameof(Score55)] = "۵۵ از ۱۰۰",
        [nameof(Score65)] = "۶۵ از ۱۰۰",
        [nameof(Score75)] = "۷۵ از ۱۰۰",
        [nameof(Score85)] = "۸۵ از ۱۰۰",
        [nameof(Failures1)] = "۱ بار",
        [nameof(Failures2)] = "۲ بار",
        [nameof(Failures3)] = "۳ بار",
        [nameof(Hours6)] = "هر ۶ ساعت",
        [nameof(Hours12)] = "هر ۱۲ ساعت",
        [nameof(Hours24)] = "هر ۲۴ ساعت",
        [nameof(Hours72)] = "هر ۳ روز",
        [nameof(CategoryAll)] = "همه بخش‌ها",
        [nameof(ListTitleAll)] = "همه DNSها",
        [nameof(ListTitleAi)] = "DNS برای هوش مصنوعی",
        [nameof(ListTitleDev)] = "DNS برای برنامه‌نویسی",
        [nameof(ListTitleGame)] = "DNS برای بازی",
        [nameof(ListSubAll)] = "مرتب‌سازی بر اساس امتیاز، پینگ و دسترسی واقعی سرویس‌ها.",
        [nameof(ListSubAi)] = "ChatGPT، Gemini، Claude و APIهای اصلی با هر DNS مقایسه می‌شوند.",
        [nameof(ListSubDev)] = "GitHub، Docker، npm، PyPI و NuGet تست می‌شوند.",
        [nameof(ListSubGame)] = "پلتفرم‌های بازی با چند Endpoint؛ سبز یعنی مسیر اصلی در دسترس است.",
        [nameof(BusyTesting)] = "در حال تست…",
        ["NoAdapter"] = "کارت شبکه پیدا نشد",
        ["InvalidUrl"] = "آدرس سایت معتبر نیست",
        ["EmptyUrlHint"] = "یک دامنه مثل google.com وارد کن.",
        ["UrlHint"] = "نمونه: google.com یا https://google.com",
        ["HttpOnly"] = "فقط HTTP و HTTPS قابل تست هستند.",
        ["DnsMissing"] = "DNS پیدا نشد",
        ["DnsListEmpty"] = "فهرست DNS خالی است.",
        ["SiteDone"] = "تست سایت کامل شد",
        ["SiteNone"] = "DNS موفق پیدا نشد",
        ["SiteDoneMsg"] = "{0} DNS توانستند {1} را باز کنند.",
        ["SiteNoneMsg"] = "هیچ DNSی نتوانست {0} را باز کند.",
        ["BestUnknown"] = "هنوز بهترین DNS مشخص نشده",
        ["BestUnknownHint"] = "ابتدا تست همه DNSها را اجرا کن.",
        ["NoAdapterSelected"] = "کارت شبکه انتخاب نشده",
        ["PickAdapter"] = "یک کارت شبکه فعال انتخاب کن.",
        ["DnsChanged"] = "DNS تغییر کرد",
        ["DnsChangedMsg"] = "{0} روی {1} فعال شد.",
        ["DnsFailed"] = "تغییر DNS ناموفق بود",
        ["NoSnapshot"] = "تنظیم قبلی ثبت نشده",
        ["NoSnapshotHint"] = "DNSYar هنوز DNS این کارت را تغییر نداده است.",
        ["RestoreOk"] = "DNS قبلی بازگردانده شد",
        ["RestoreOkMsg"] = "تنظیم قبلی: {0}",
        ["DhcpMode"] = "حالت خودکار (DHCP)",
        ["RestoreFail"] = "بازگردانی ناموفق بود",
        ["NothingToRestore"] = "چیزی برای بازگردانی نیست",
        ["NothingToRestoreHint"] = "هیچ تنظیم قبلی ذخیره نشده است.",
        ["RestoreAllOk"] = "بازگردانی کامل شد",
        ["RestoreAllOkMsg"] = "تنظیم قبلی {0} کارت شبکه بازیابی شد.",
        ["RestorePartial"] = "بازگردانی ناقص بود",
        ["RestorePartialMsg"] = "{0} مورد بازیابی شد. {1} مورد خطا داشت: {2}",
        ["TrayHiddenTitle"] = "DNSYar همچنان فعال است",
        ["TrayHiddenMsg"] = "برنامه در System Tray است. برای خروج کامل از منوی Tray استفاده کن.",
        ["CatalogBusy"] = "بروزرسانی در حال اجراست",
        ["CatalogBusyHint"] = "تا پایان دریافت فعلی صبر کن.",
        ["CatalogEmptyUrl"] = "آدرس بروزرسانی خالی است",
        ["CatalogEmptyUrlHint"] = "لینک فایل GitHub را وارد کن یا منبع پیش‌فرض را بزن.",
        ["CatalogOk"] = "بروزرسانی انجام شد",
        ["CatalogOkMsg"] = "{0} DNS جدید، {1} مورد به‌روز شد. فرمت: {2}. DNSهای دستی حفظ شدند.",
        ["CatalogFail"] = "بروزرسانی ناموفق بود",
        ["CustomName"] = "نام DNS",
        ["CustomNamePh"] = "مثال: DNS شرکت من",
        ["CustomPrimary"] = "Primary IPv4",
        ["CustomSecondary"] = "Secondary IPv4 (اختیاری)",
        ["CustomDoh"] = "DoH URL (اختیاری)",
        ["CustomCategory"] = "نمایش در بخش",
        ["CustomNote"] = "DNS دستی فقط روی همین سیستم ذخیره می‌شود و GitHub آن را حذف نمی‌کند.",
        ["CustomAdd"] = "افزودن",
        ["CustomCancel"] = "انصراف",
        ["CustomTitle"] = "افزودن DNS دستی",
        ["NameEmpty"] = "نام DNS خالی است",
        ["NameEmptyHint"] = "برای DNS یک نام وارد کن.",
        ["PrimaryInvalid"] = "Primary نامعتبر است",
        ["PrimaryInvalidHint"] = "یک IPv4 معتبر وارد کن.",
        ["SecondaryInvalid"] = "Secondary نامعتبر است",
        ["DohInvalid"] = "DoH نامعتبر است",
        ["DohInvalidHint"] = "آدرس DoH باید HTTPS کامل باشد.",
        ["DuplicateDns"] = "DNS تکراری است",
        ["DuplicateDnsHint"] = "این Primary از قبل وجود دارد.",
        ["CustomSaved"] = "DNS اضافه شد",
        ["CustomSavedMsg"] = "{0} ذخیره شد.",
        ["CustomDescription"] = "DNS دستی افزوده‌شده توسط کاربر",
        ["SourceReset"] = "منبع GitHub بازگردانی شد",
        ["SourceResetHint"] = "منبع پیش‌فرض فعال شد.",
        ["LastUpdateNever"] = "آخرین بروزرسانی: هنوز انجام نشده",
        ["LastUpdate"] = "آخرین بروزرسانی: {0:yyyy/MM/dd HH:mm}",
        ["NoRestoreTray"] = "تنظیم قبلی برای بازگردانی وجود ندارد.",
        ["RestoreTrayOk"] = "تنظیم DNS قبلی بازگردانده شد.",
        ["SmartNoTarget"] = "برای این پروفایل DNS یا Endpoint کافی نیست.",
        ["SmartHealthy"] = "{0} سالم است · {1}/100 · بدون تغییر",
        ["SmartDrop"] = "افت کیفیت {0} · {1}/{2} تا Failover",
        ["SmartNone"] = "جایگزین سالمی پیدا نشد؛ DNS فعلی ماند.",
        ["SmartNoneHint"] = "Failover انجام نشد.",
        ["SmartSame"] = "بهترین گزینه همچنان {0} است · {1}/100",
        ["SmartFailApply"] = "{0} انتخاب شد اما اعمال نشد.",
        ["SmartSwitched"] = "Failover: {0} ← {1} · {2}/100",
        ["SmartSwitchedHint"] = "بهترین گزینه فعال شد: {0} ({1}/100)",
        ["CurrentDns"] = "DNS فعلی",
        ["SmartError"] = "خطا: {0}",
        ["SmartFailTitle"] = "Smart Auto ناموفق بود",
        ["SmartStarted"] = "پایش دوره‌ای شروع شد",
        ["SmartStopped"] = "پایش متوقف شد",
        ["SmartOnMsg"] = "پایش و Failover فعال شد.",
        ["SmartOffMsg"] = "پایش خودکار خاموش شد.",
        ["ProfileChanged"] = "پروفایل تغییر کرد",
        ["StartupError"] = "خطا در راه‌اندازی",
        ["ErrorPrefix"] = "خطا: {0}",
        ["AutoTestError"] = "خطا در تست خودکار",
        ["TestingNamed"] = "در حال تست {0}…",
        ["ApplyingNamed"] = "در حال اعمال {0}…",
        ["Restoring"] = "در حال بازگردانی…",
        ["RestoringAll"] = "در حال بازگردانی همه…",
        ["TestingAll"] = "در حال تست همه DNSها…",
        ["TestingSection"] = "در حال تست این بخش…",
        ["CatalogBusyOverlay"] = "در حال دریافت DNSهای GitHub…",
        ["SmartBusy"] = "Smart Auto در حال بررسی…",
        ["Cancelled"] = "تست لغو شد یا زمان آن تمام شد",
        ["DnsTimeout"] = "پاسخی برای دامنه دریافت نشد",
        ["SiteTesting"] = "در حال تست…",
        ["SiteTestingDetail"] = "در حال Resolve و بررسی اتصال",
        ["SiteOpen"] = "باز می‌شود",
        ["SiteClosed"] = "باز نمی‌شود",
        ["SiteOk"] = "اتصال واقعی موفق بود",
        ["SiteOkHost"] = "موفق · {0}",
        ["SiteHttpFail"] = "DNS پاسخ داد، اما سایت باز نشد",
        ["SiteDnsFail"] = "این DNS دامنه را Resolve نکرد",
        ["HttpTimeout"] = "مهلت اتصال تمام شد",
        ["CoverageAi"] = "{0} مسیر AI",
        ["CoverageDev"] = "{0} مسیر توسعه",
        ["CoverageGame"] = "{0} پلتفرم · {1} Endpoint",
        ["CoverageAiShort"] = "{0} Endpoint هوش مصنوعی",
        ["CoverageDevShort"] = "{0} Endpoint برنامه‌نویسی",
        ["CoverageAll"] = "{0} DNS · {1} Endpoint",
        ["CoverageGameList"] = "{0} پلتفرم · {1} Endpoint · {2}",
        ["RecGameStrong"] = "پیشنهاد قوی برای بازی؛ دسترسی و تاخیر مناسب است",
        ["RecGameOk"] = "مناسب بازی؛ بعضی پلتفرم‌ها محدود هستند",
        ["RecGameNo"] = "برای سرویس‌های بازی پیشنهاد نمی‌شود",
        ["RecAll"] = "پیشنهاد عمومی برای AI، توسعه و بازی",
        ["RecAiDev"] = "پیشنهاد برای هوش مصنوعی و برنامه‌نویسی",
        ["RecAi"] = "پیشنهاد برای ChatGPT، Gemini و سرویس‌های AI",
        ["RecDev"] = "پیشنهاد برای GitHub، Docker، npm و ابزارهای توسعه",
        ["RecGame"] = "پیشنهاد مناسب برای سرویس‌های بازی",
        ["RecMixed"] = "مناسب استفاده عمومی؛ بعضی سرویس‌ها محدود هستند",
        ["RecNo"] = "برای سرویس‌های هدف پیشنهاد نمی‌شود",
        ["NoTargets"] = "سرویس هدفی تعریف نشده است.",
        ["TrayOpen"] = "باز کردن DNSYar",
        ["TrayQuick"] = "تغییر سریع DNS",
        ["TraySmart"] = "Smart Auto DNS",
        ["TrayTestNow"] = "بررسی هوشمند الآن",
        ["TrayRestore"] = "بازگردانی DNS قبلی",
        ["TrayExit"] = "خروج کامل از DNSYar",
        ["TrayEmpty"] = "DNSی موجود نیست",
        ["TrayActive"] = "DNS فعال: {0}",
        ["SmartStatus"] = "{0} · {1} · {2}",
        ["HomeSmartOn"] = "فعال · {0}",
        ["NotTested"] = "هنوز تست نشده",
        ["ServiceDetailsHint"] = "برای دیدن وضعیت سرویس‌ها تست را اجرا کن.",
        ["InternalSource"] = "داخلی",
        ["BestPingFmt"] = "پینگ: {0}",
        ["BestDnsFmt"] = "DNS: {0}",
        ["BestServicesFmt"] = "سرویس‌ها: {0}",
        ["SiteWaiting"] = "در انتظار تست",
        ["DnsPending"] = "DNS: —",
        ["HttpPending"] = "HTTP: —",
        ["DnsEllipsis"] = "DNS: …",
        ["HttpEllipsis"] = "HTTP: …",
        ["DnsNoReply"] = "DNS: بدون پاسخ",
        ["DnsMsFmt"] = "DNS: {0:0} ms",
        ["HttpOkFmt"] = "HTTP: {0:0} ms • {1}",
        ["HttpErrFmt"] = "HTTP: خطا • {0}",
        ["HttpFail"] = "HTTP: ناموفق",
        ["IpNone"] = "IP: —",
        ["IpEllipsis"] = "IP: …",
        ["IpFmt"] = "IP: {0}",
        ["CatalogHttpsRequired"] = "آدرس بروزرسانی باید یک URL معتبر HTTPS باشد.",
        ["CatalogEmpty"] = "فهرست DNS دریافتی خالی است.",
        ["CatalogNoIpv4"] = "هیچ DNS معتبر IPv4 در منبع GitHub پیدا نشد.",
        ["CatalogJsonUnsupported"] = "ساختار JSON منبع DNS پشتیبانی نمی‌شود.",
        ["CatalogGithubDesc"] = "افزوده‌شده خودکار از GitHub • دسته منبع: {0}",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        [nameof(NavHome)] = "Home",
        [nameof(NavAi)] = "AI",
        [nameof(NavDev)] = "Developer",
        [nameof(NavGame)] = "Gaming",
        [nameof(NavAll)] = "All DNS",
        [nameof(NavSite)] = "Site test",
        [nameof(NavSettings)] = "Settings",
        [nameof(BrandKicker)] = "Smart DNS Manager",
        [nameof(Creator)] = "Author",
        [nameof(HeroKicker)] = "Smart DNS · Windows",
        [nameof(HeroTitle)] = "Find the cleanest path",
        [nameof(HeroSubtitle)] = "Compare ping, DNS resolve, and real reachability for AI, developer, and game services — without the noise.",
        [nameof(TestAll)] = "Test all",
        [nameof(SmartNow)] = "Run Smart Auto",
        [nameof(RestoreDns)] = "Restore DNS",
        [nameof(MetricActive)] = "Active DNS",
        [nameof(MetricScore)] = "Best score",
        [nameof(MetricAdapter)] = "Adapter",
        [nameof(MetricProviders)] = "Resolvers",
        [nameof(MetricSmart)] = "Smart Auto",
        [nameof(Recommend)] = "Pick",
        [nameof(RecommendEmpty)] = "Not tested yet",
        [nameof(RecommendHint)] = "Run Test all to rank resolvers.",
        [nameof(Connect)] = "Connect",
        [nameof(Test)] = "Test",
        [nameof(AdapterTitle)] = "Network adapter",
        [nameof(AdapterHint)] = "DNS is applied only to the selected adapter.",
        [nameof(Coverage)] = "Probe coverage",
        [nameof(AddCustom)] = "+ Custom DNS",
        [nameof(TestSection)] = "Test this list",
        [nameof(SearchPlaceholder)] = "Search by name or IP",
        [nameof(GreenMeansOk)] = "Green = reachable",
        [nameof(SiteTitle)] = "Site test",
        [nameof(SiteKicker)] = "Windows DNS stays unchanged",
        [nameof(SiteHint)] = "Enter a domain. Each resolver is queried on its own, then a real HTTP connection is opened.",
        [nameof(SitePlaceholder)] = "google.com  or  https://chatgpt.com",
        [nameof(SiteTested)] = "Tested",
        [nameof(SiteReachable)] = "Reachable",
        [nameof(SiteFailed)] = "Failed",
        [nameof(SiteFastest)] = "Fastest success",
        [nameof(SiteEmptyTitle)] = "Enter a domain",
        [nameof(SiteEmptyHint)] = "Each resolver lights up green or red as it finishes.",
        [nameof(SettingsTitle)] = "Settings",
        [nameof(SettingsSubtitle)] = "Language, look, Smart Auto, and safe restore",
        [nameof(LanguageTitle)] = "Language",
        [nameof(LanguageHint)] = "Persian is right-to-left; English is left-to-right. The matching bundled font is applied.",
        [nameof(AppearanceTitle)] = "Appearance",
        [nameof(AppearanceHint)] = "Minimal themes and bundled fonts",
        [nameof(FontLabel)] = "Font",
        [nameof(ThemeLabel)] = "Theme",
        [nameof(FontHint)] = "Vazirmatn (Persian) and Inter (English) ship with the app. Segoe UI comes from Windows.",
        [nameof(FontAuto)] = "Auto (follow language)",
        [nameof(ThemePaper)] = "Paper",
        [nameof(ThemeInk)] = "Ink",
        [nameof(ThemeSignal)] = "Signal",
        [nameof(SmartTitle)] = "Smart Auto + Failover",
        [nameof(SmartHint)] = "Switch only after a real quality drop",
        [nameof(SmartToggle)] = "Automatic DNS selection and failover",
        [nameof(ProfileLabel)] = "Profile",
        [nameof(IntervalLabel)] = "Check interval",
        [nameof(MinScoreLabel)] = "Minimum replacement score",
        [nameof(FailuresLabel)] = "Failover after consecutive drops",
        [nameof(ProfileAll)] = "All-purpose",
        [nameof(ProfileAi)] = "AI",
        [nameof(ProfileDev)] = "Developer",
        [nameof(ProfileGame)] = "Gaming",
        [nameof(MonitorStatus)] = "Monitor status",
        [nameof(RunNow)] = "Run now",
        [nameof(SmartExplain)] = "The active DNS is probed first. After consecutive drops, matching resolvers are ranked and the healthiest one is applied.",
        [nameof(TrayTitle)] = "System Tray",
        [nameof(TrayHint)] = "Quick controls next to the clock",
        [nameof(TrayToggle)] = "Show DNSYar in the system tray",
        [nameof(CloseToTray)] = "Close button hides to tray",
        [nameof(ExitBehaviorTitle)] = "Exit behavior",
        [nameof(ExitBehaviorMessage)] = "Off by default: × exits and restores DNS. When on, × only hides; full exit from the tray still restores DNS.",
        [nameof(TrayExplain)] = "Menu: active DNS, quick switch, Smart Auto, instant test, restore, and full exit.",
        [nameof(CatalogTitle)] = "GitHub catalog",
        [nameof(CatalogHint)] = "Safe merge with your local list",
        [nameof(AutoUpdateToggle)] = "Fetch new DNS entries automatically",
        [nameof(CatalogKeepCustom)] = "Custom DNS entries are never removed by a GitHub update.",
        [nameof(UpdateUrlLabel)] = "File URL — JSON or TXT",
        [nameof(DefaultSource)] = "Default source",
        [nameof(UpdateIntervalLabel)] = "Update interval",
        [nameof(DefaultSourceHint)] = "Default source: Iran-DNS-Switcher / dns_servers.txt",
        [nameof(CheckUpdate)] = "Check now",
        [nameof(RestoreTitle)] = "Safe restore",
        [nameof(RestoreHint)] = "Keep the DNS you had before DNSYar",
        [nameof(RestoreOnExit)] = "Restore previous DNS on exit or shutdown",
        [nameof(CrashRecovery)] = "Recover previous DNS on the next launch after a crash",
        [nameof(RestoreNoteTitle)] = "Note",
        [nameof(RestoreNoteMessage)] = "The real adapter state is saved before the first change. Manual DNS is restored exactly; DHCP returns to DHCP.",
        [nameof(RestoreAdapter)] = "Restore this adapter",
        [nameof(RestoreAll)] = "Restore all",
        [nameof(AboutTitle)] = "About DNSYar",
        [nameof(AboutSubtitle)] = "Smart DNS management for Windows",
        [nameof(AboutAuthor)] = "Author: Sahand Rezvan",
        [nameof(AuthorName)] = "Sahand Rezvan",
        [nameof(LabelPing)] = "Ping",
        [nameof(LabelDns)] = "DNS",
        [nameof(LabelLoss)] = "Loss",
        [nameof(LabelServices)] = "Services",
        [nameof(Off)] = "Off",
        [nameof(On)] = "On",
        [nameof(Ready)] = "Ready",
        [nameof(Active)] = "Active",
        [nameof(CustomSource)] = "Custom · local",
        [nameof(ReadyToTest)] = "Ready to test",
        [nameof(Testing)] = "Testing…",
        [nameof(StatusExcellent)] = "Excellent",
        [nameof(StatusGood)] = "Good",
        [nameof(StatusFair)] = "Fair",
        [nameof(StatusWeak)] = "Weak",
        [nameof(Interval5)] = "Every 5 minutes",
        [nameof(Interval10)] = "Every 10 minutes",
        [nameof(Interval15)] = "Every 15 minutes",
        [nameof(Interval30)] = "Every 30 minutes",
        [nameof(Interval60)] = "Every 60 minutes",
        [nameof(Score55)] = "55 / 100",
        [nameof(Score65)] = "65 / 100",
        [nameof(Score75)] = "75 / 100",
        [nameof(Score85)] = "85 / 100",
        [nameof(Failures1)] = "1 drop",
        [nameof(Failures2)] = "2 drops",
        [nameof(Failures3)] = "3 drops",
        [nameof(Hours6)] = "Every 6 hours",
        [nameof(Hours12)] = "Every 12 hours",
        [nameof(Hours24)] = "Every 24 hours",
        [nameof(Hours72)] = "Every 3 days",
        [nameof(CategoryAll)] = "All sections",
        [nameof(ListTitleAll)] = "All DNS",
        [nameof(ListTitleAi)] = "DNS for AI",
        [nameof(ListTitleDev)] = "DNS for developers",
        [nameof(ListTitleGame)] = "DNS for gaming",
        [nameof(ListSubAll)] = "Ranked by score, ping, and real service reachability.",
        [nameof(ListSubAi)] = "ChatGPT, Gemini, Claude, and core APIs are compared on each resolver.",
        [nameof(ListSubDev)] = "GitHub, Docker, npm, PyPI, and NuGet are probed.",
        [nameof(ListSubGame)] = "Game platforms with multiple endpoints; green means the main path is up.",
        [nameof(BusyTesting)] = "Testing…",
        ["NoAdapter"] = "No adapter found",
        ["InvalidUrl"] = "Invalid site address",
        ["EmptyUrlHint"] = "Enter a domain such as google.com.",
        ["UrlHint"] = "Example: google.com or https://google.com",
        ["HttpOnly"] = "Only HTTP and HTTPS addresses can be tested.",
        ["DnsMissing"] = "No DNS found",
        ["DnsListEmpty"] = "The DNS list is empty.",
        ["SiteDone"] = "Site test finished",
        ["SiteNone"] = "No working DNS",
        ["SiteDoneMsg"] = "{0} resolvers opened {1}.",
        ["SiteNoneMsg"] = "None of the current resolvers could open {0}.",
        ["BestUnknown"] = "Best DNS is not ranked yet",
        ["BestUnknownHint"] = "Run Test all first.",
        ["NoAdapterSelected"] = "No adapter selected",
        ["PickAdapter"] = "Choose an active network adapter.",
        ["DnsChanged"] = "DNS applied",
        ["DnsChangedMsg"] = "{0} is now active on {1}.",
        ["DnsFailed"] = "Could not apply DNS",
        ["NoSnapshot"] = "Nothing stored to restore",
        ["NoSnapshotHint"] = "DNSYar has not changed DNS on this adapter yet.",
        ["RestoreOk"] = "Previous DNS restored",
        ["RestoreOkMsg"] = "Restored: {0}",
        ["DhcpMode"] = "Automatic (DHCP)",
        ["RestoreFail"] = "Restore failed",
        ["NothingToRestore"] = "Nothing to restore",
        ["NothingToRestoreHint"] = "No previous DNS snapshot is stored.",
        ["RestoreAllOk"] = "Restore complete",
        ["RestoreAllOkMsg"] = "Previous DNS restored on {0} adapter(s).",
        ["RestorePartial"] = "Restore incomplete",
        ["RestorePartialMsg"] = "{0} restored. {1} failed: {2}",
        ["TrayHiddenTitle"] = "DNSYar is still running",
        ["TrayHiddenMsg"] = "The app is in the system tray. Use the tray menu for a full exit.",
        ["CatalogBusy"] = "Update already running",
        ["CatalogBusyHint"] = "Wait for the current download to finish.",
        ["CatalogEmptyUrl"] = "Update URL is empty",
        ["CatalogEmptyUrlHint"] = "Paste a GitHub file URL or reset to the default source.",
        ["CatalogOk"] = "Catalog updated",
        ["CatalogOkMsg"] = "{0} new, {1} updated. Format: {2}. Custom entries kept.",
        ["CatalogFail"] = "Update failed",
        ["CustomName"] = "DNS name",
        ["CustomNamePh"] = "e.g. Office DNS",
        ["CustomPrimary"] = "Primary IPv4",
        ["CustomSecondary"] = "Secondary IPv4 (optional)",
        ["CustomDoh"] = "DoH URL (optional)",
        ["CustomCategory"] = "Show in",
        ["CustomNote"] = "Custom DNS stays on this PC and is never removed by GitHub updates.",
        ["CustomAdd"] = "Add",
        ["CustomCancel"] = "Cancel",
        ["CustomTitle"] = "Add custom DNS",
        ["NameEmpty"] = "Name is empty",
        ["NameEmptyHint"] = "Give this DNS a name.",
        ["PrimaryInvalid"] = "Invalid primary",
        ["PrimaryInvalidHint"] = "Enter a valid IPv4 address.",
        ["SecondaryInvalid"] = "Invalid secondary",
        ["DohInvalid"] = "Invalid DoH",
        ["DohInvalidHint"] = "DoH must be a full HTTPS URL.",
        ["DuplicateDns"] = "Duplicate DNS",
        ["DuplicateDnsHint"] = "This primary address is already in the list.",
        ["CustomSaved"] = "DNS added",
        ["CustomSavedMsg"] = "{0} was saved.",
        ["CustomDescription"] = "Custom DNS added by the user",
        ["SourceReset"] = "GitHub source reset",
        ["SourceResetHint"] = "The default source is active.",
        ["LastUpdateNever"] = "Last update: not yet",
        ["LastUpdate"] = "Last update: {0:yyyy-MM-dd HH:mm}",
        ["NoRestoreTray"] = "No previous DNS is stored to restore.",
        ["RestoreTrayOk"] = "Previous DNS restored.",
        ["SmartNoTarget"] = "Not enough DNS or endpoints for this profile.",
        ["SmartHealthy"] = "{0} is healthy · {1}/100 · no change",
        ["SmartDrop"] = "Quality drop on {0} · {1}/{2} until failover",
        ["SmartNone"] = "No healthy replacement; current DNS kept.",
        ["SmartNoneHint"] = "Failover did not run.",
        ["SmartSame"] = "{0} is still the best · {1}/100",
        ["SmartFailApply"] = "{0} was chosen but could not be applied.",
        ["SmartSwitched"] = "Failover: {0} → {1} · {2}/100",
        ["SmartSwitchedHint"] = "Now active: {0} ({1}/100)",
        ["CurrentDns"] = "Current DNS",
        ["SmartError"] = "Error: {0}",
        ["SmartFailTitle"] = "Smart Auto failed",
        ["SmartStarted"] = "Periodic monitoring started",
        ["SmartStopped"] = "Monitoring paused",
        ["SmartOnMsg"] = "Monitoring and failover are on.",
        ["SmartOffMsg"] = "Automatic monitoring is off.",
        ["ProfileChanged"] = "Profile changed",
        ["StartupError"] = "Startup error",
        ["ErrorPrefix"] = "Error: {0}",
        ["AutoTestError"] = "Automatic test error",
        ["TestingNamed"] = "Testing {0}…",
        ["ApplyingNamed"] = "Applying {0}…",
        ["Restoring"] = "Restoring DNS…",
        ["RestoringAll"] = "Restoring all adapters…",
        ["TestingAll"] = "Testing every DNS…",
        ["TestingSection"] = "Testing this section…",
        ["CatalogBusyOverlay"] = "Fetching GitHub DNS list…",
        ["SmartBusy"] = "Smart Auto is checking…",
        ["Cancelled"] = "The test was cancelled or timed out",
        ["DnsTimeout"] = "No response for this domain",
        ["SiteTesting"] = "Testing…",
        ["SiteTestingDetail"] = "Resolving and opening a real connection",
        ["SiteOpen"] = "Opens",
        ["SiteClosed"] = "Blocked",
        ["SiteOk"] = "Real connection succeeded",
        ["SiteOkHost"] = "OK · {0}",
        ["SiteHttpFail"] = "DNS answered, but the site did not open",
        ["SiteDnsFail"] = "This DNS did not resolve the domain",
        ["HttpTimeout"] = "Connection timed out",
        ["CoverageAi"] = "{0} AI paths",
        ["CoverageDev"] = "{0} developer paths",
        ["CoverageGame"] = "{0} platforms · {1} endpoints",
        ["CoverageAiShort"] = "{0} AI endpoints",
        ["CoverageDevShort"] = "{0} developer endpoints",
        ["CoverageAll"] = "{0} DNS · {1} endpoints",
        ["CoverageGameList"] = "{0} platforms · {1} endpoints · {2}",
        ["RecGameStrong"] = "Strong pick for gaming; reachability and latency look good",
        ["RecGameOk"] = "Fine for gaming; some platforms are limited",
        ["RecGameNo"] = "Not recommended for game services",
        ["RecAll"] = "Good general pick for AI, development, and gaming",
        ["RecAiDev"] = "Recommended for AI and development",
        ["RecAi"] = "Recommended for ChatGPT, Gemini, and AI services",
        ["RecDev"] = "Recommended for GitHub, Docker, npm, and developer tools",
        ["RecGame"] = "A solid pick for game services",
        ["RecMixed"] = "Usable in general; some services are limited",
        ["RecNo"] = "Not recommended for the target services",
        ["NoTargets"] = "No probe targets are defined.",
        ["TrayOpen"] = "Open DNSYar",
        ["TrayQuick"] = "Quick switch",
        ["TraySmart"] = "Smart Auto DNS",
        ["TrayTestNow"] = "Run Smart Check",
        ["TrayRestore"] = "Restore previous DNS",
        ["TrayExit"] = "Quit DNSYar",
        ["TrayEmpty"] = "No DNS available",
        ["TrayActive"] = "Active DNS: {0}",
        ["SmartStatus"] = "{0} · {1} · {2}",
        ["HomeSmartOn"] = "On · {0}",
        ["NotTested"] = "Not tested yet",
        ["ServiceDetailsHint"] = "Run a test to see service reachability.",
        ["InternalSource"] = "Built-in",
        ["BestPingFmt"] = "Ping: {0}",
        ["BestDnsFmt"] = "DNS: {0}",
        ["BestServicesFmt"] = "Services: {0}",
        ["SiteWaiting"] = "Waiting",
        ["DnsPending"] = "DNS: —",
        ["HttpPending"] = "HTTP: —",
        ["DnsEllipsis"] = "DNS: …",
        ["HttpEllipsis"] = "HTTP: …",
        ["DnsNoReply"] = "DNS: no answer",
        ["DnsMsFmt"] = "DNS: {0:0} ms",
        ["HttpOkFmt"] = "HTTP: {0:0} ms • {1}",
        ["HttpErrFmt"] = "HTTP: error • {0}",
        ["HttpFail"] = "HTTP: failed",
        ["IpNone"] = "IP: —",
        ["IpEllipsis"] = "IP: …",
        ["IpFmt"] = "IP: {0}",
        ["CatalogHttpsRequired"] = "The update address must be a valid HTTPS URL.",
        ["CatalogEmpty"] = "The downloaded DNS list is empty.",
        ["CatalogNoIpv4"] = "No valid IPv4 DNS entries were found in the GitHub source.",
        ["CatalogJsonUnsupported"] = "This DNS JSON layout is not supported.",
        ["CatalogGithubDesc"] = "Added automatically from GitHub • source category: {0}",
    };
}
